### PR TITLE
Added Feature/UI init

### PR DESCRIPTION
**Pull request by Manan-Sharma-5**
## Summary by CodeRabbit

- **New Features**
	- Introduced a new layout component for improved theming and platform support.
	- Added a new interactive survey interface for user engagement.
	- Expanded navigation structure to include new screens for collaboration opportunities.
	- Implemented a job collaboration platform interface with search and filter capabilities.
	- Enhanced pre-sign-in experience with a dynamic swiper interface.
	- Created a comprehensive collaboration card component for displaying job advertisements.

- **Bug Fixes**
	- Resolved issues with navigation and screen transitions.

- **Documentation**
	- Updated documentation to reflect new components and functionalities.

- **Style**
	- Standardized styling across various components for consistency.

- **Chores**
	- Updated dependencies and scripts in package configuration for improved performance.

### CODE REVIEW

**Review by dev-rathore — APPROVED** [review]
LGTM

**Comment by Manan-Sharma-5** [comment]
[Creating Global Stylesheet](https://trello.com/c/kbVseniS/10-creating-global-stylesheet)

**Comment by Manan-Sharma-5** [comment]
[Pre signin pages](https://trello.com/c/mNFEMfo1/3-pre-signin-pages)

**Comment by Manan-Sharma-5** [comment]
[Collaboration Listing](https://trello.com/c/ZLWw0zHD/7-collaboration-listing)

**Comment by Manan-Sharma-5** [comment]
[Onboard Questions](https://trello.com/c/kLO7Gl7s/4-onboard-questions)

**Comment by Manan-Sharma-5** [comment]
[Collaboration Details Page](https://trello.com/c/lbUj0KDg/8-collaboration-details-page)

**Comment by Manan-Sharma-5** [comment]
[Collaboration Apply Now Page](https://trello.com/c/agdXU2Ud/9-collaboration-apply-now-page)

**Comment by Manan-Sharma-5** [comment]
[Collaboration Apply Now Page](https://trello.com/c/agdXU2Ud/9-collaboration-apply-now-page)

**Pull request merged**
