### PR TITLE
made bug fixes

### PR DESCRIPTION
**Pull request by Manan-Sharma-5**
## Summary by CodeRabbit

- **New Features**
	- Enhanced user authentication process with new sign-up functionality.
	- Token-based authentication introduced for sign-in and sign-up methods.
	- Updated navigation paths after successful authentication.
	- New project configuration settings added, including project ID and owner details.

- **Bug Fixes**
	- Removed anonymous sign-in process to streamline user experience.

- **Documentation**
	- Updated method signatures in the authentication context for clarity.

### CODE REVIEW

**Comment by Manan-Sharma-5** [comment]
[Facebook user should be stored on the users collection and its using firebase user id everywhere](https://trello.com/c/M6fMlajg/90-facebook-user-should-be-stored-on-the-users-collection-and-its-using-firebase-user-id-everywhere)

**Comment by Manan-Sharma-5** [comment]
[Check Onboarding questions -> to be stored in the correct users collection](https://trello.com/c/WGRHqrUC/93-check-onboarding-questions-to-be-stored-in-the-correct-users-collection)

**Comment by Manan-Sharma-5** [comment]
[User collection might need some changes. Make sure we are complying with the user collection on the dev branch](https://trello.com/c/wlWHKaLK/91-user-collection-might-need-some-changes-make-sure-we-are-complying-with-the-user-collection-on-the-dev-branch)

**Comment by Manan-Sharma-5** [comment]
[Setup Expo Dev - for cloud building](https://trello.com/c/rZQHrNl1/29-setup-expo-dev-for-cloud-building)

**Review by dev-rathore — APPROVED** [review]

**Pull request merged**
