### PR TITLE
ui fixes

### PR DESCRIPTION
**Pull request by Manan-Sharma-5**
## Release Notes

- **New Features**
  - Updated application icon to a new JPG format for improved visual appeal.
  - Enhanced ProposalScreen with a new button and image for better user interaction.

- **Improvements**
  - Streamlined user interface in various components by removing unnecessary console logs and simplifying layouts.
  - Improved search functionality with the integration of a new Searchbar component.

- **Bug Fixes**
  - Fixed issues related to image rendering by providing default images when logos are unavailable.

- **Style Changes**
  - Adjusted margins and paddings in various styles for better layout control. 
  - Added a new subtitle style for improved text presentation in proposals.

### CODE REVIEW

**Comment by Manan-Sharma-5** [comment]
[Invitations, Applications and Contracts page -> Card Padding should be equal to the feedback given for collaborations page](https://trello.com/c/pBWR6IL3/98-invitations-applications-and-contracts-page-card-padding-should-be-equal-to-the-feedback-given-for-collaborations-page)

**Comment by Manan-Sharma-5** [comment]
[Contracts page - Data is not integrated with Firestore](https://trello.com/c/qqLjJx3g/99-contracts-page-data-is-not-integrated-with-firestore)

**Comment by Manan-Sharma-5** [comment]
[Invitations -> Bottom section issue](https://trello.com/c/CsrRodDS/101-invitations-bottom-section-issue)

**Comment by Manan-Sharma-5** [comment]
[Search bar looks different for Collaborations and Message screen. Match the message screeb design](https://trello.com/c/cOhaLycy/105-search-bar-looks-different-for-collaborations-and-message-screen-match-the-message-screeb-design)

**Comment by Manan-Sharma-5** [comment]
[Invitations -> Data seems to be not integrated](https://trello.com/c/19lo2okl/118-invitations-data-seems-to-be-not-integrated)

**Comment by Manan-Sharma-5** [comment]
[Header Size for Applications, Contracts and Collaborations looks different. Make it exactly identical to that of Message header size](https://trello.com/c/i7OsIZ0E/104-header-size-for-applications-contracts-and-collaborations-looks-different-make-it-exactly-identical-to-that-of-message-header-si)

**Comment by Manan-Sharma-5** [comment]
[Applications page - Empty illustration should be better](https://trello.com/c/K4xhj98p/100-applications-page-empty-illustration-should-be-better)

**Comment by Manan-Sharma-5** [comment]
[For all the cards (Applications, Invitations, Collaborations and Contracts) -> make the changes as mentioned in screenshot](https://trello.com/c/q05iWcpi/108-for-all-the-cards-applications-invitations-collaborations-and-contracts-make-the-changes-as-mentioned-in-screenshot)

**Comment by Manan-Sharma-5** [comment]
[Collaboration Details - Show a placeholder image when no banner](https://trello.com/c/pDobkIWx/106-collaboration-details-show-a-placeholder-image-when-no-banner)

**Review by dev-rathore — APPROVED** [review]

**Pull request merged**
